"""
RAG Pipeline — Retrieval-Augmented Generation Flow

Connects retrieval and generation into a single pipeline:
Retrieve similar clauses → Augment the prompt with context → Generate analysis.
"""

import logging

from src.embeddings import load_clause_database
from src.output_parser import parse_json_response_or_raw
from src.retrieval import search_similar_clauses, format_retrieval_results
from src.generation import (
    build_basic_prompt,
    build_structured_prompt,
    build_few_shot_prompt,
    generate_analysis,
)

logger = logging.getLogger(__name__)

# Map strategy names to their prompt builders
STRATEGIES = {
    "basic": build_basic_prompt,
    "structured": build_structured_prompt,
    "few_shot": build_few_shot_prompt,
}

_DISCLAIMER = (
    "DRAFT ANALYSIS — Requires Attorney Review. "
    "This analysis was generated by an AI system and has not been "
    "reviewed by a licensed attorney. Do not rely on this output "
    "as legal advice."
)


def analyze_clause(
    clause_text: str,
    db: dict,
    strategy: str = "few_shot",
    top_k: int = 3,
    model: str | None = None,
    temperature: float = 0.2,
) -> dict:
    """
    Full RAG pipeline: retrieve similar clauses, then generate analysis.

    Returns the parsed analysis alongside a source trail, draft framing,
    and pipeline metadata for explainability and audit trail purposes.
    """
    logger.info("Analyzing clause with strategy=%s, top_k=%d", strategy, top_k)
    retrieved = search_similar_clauses(clause_text, db, top_k=top_k)
    context = format_retrieval_results(retrieved)

    prompt_builder = STRATEGIES[strategy]
    messages = prompt_builder(clause_text, context)

    raw_analysis = generate_analysis(
        messages, db["provider"], model=model, temperature=temperature
    )

    # Parse the LLM response into structured JSON
    parsed = parse_json_response_or_raw(raw_analysis)

    # Build source trail from retrieval results
    sources = []
    for r in retrieved:
        clause = r["clause"]
        sources.append({
            "id": clause.get("id", "unknown"),
            "title": clause.get("title", ""),
            "score": round(r["score"], 4),
            "risk_level": clause.get("risk_level", ""),
        })

    logger.info("Analysis complete (strategy=%s, model=%s)", strategy, model or db["provider"].chat_model)
    return {
        "analysis": parsed,
        "sources": sources,
        "strategy": strategy,
        "model": model or db["provider"].chat_model,
        "top_k": top_k,
        "review_status": "pending_review",
        "disclaimer": _DISCLAIMER,
    }
